openapi: 3.0.0
info:
	name: STD23031-TD1
	version: 1.0.0
serveurs:
	-url: http://localhost.STD23031.com
paths:
	/customers:
		get:
			responses:
				200:
    					content:
						application/json
							schema:
								type: object
								items:
									$ref: '#/components/schemas/Customer'
components:
	schemas:
		Customer:
			type: object
			properties:
				name:
					type: string
				age:
					type: integer
